const PDFDocument = require('pdfkit');

/**
 * Generate PDF from email content
 * @param {Object} emailData - {subject, body, applicantName, recruiterName, recruiterCompany}
 * @returns {PDFDocument} - Readable stream
 */
function generateEmailPDF(emailData) {
  const { subject, body, applicantName, recruiterName, recruiterCompany, createdAt } = emailData;

  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 50, bottom: 50, left: 50, right: 50 }
  });

  // Header
  doc.fontSize(20).font('Helvetica-Bold').text('Cold Outreach Email', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(10).font('Helvetica').fillColor('#666').text(`Generated on ${new Date(createdAt || Date.now()).toLocaleDateString()}`, { align: 'center' });
  doc.moveDown(1);

  // Divider line
  doc.strokeColor('#cccccc').lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(1);

  // Metadata section
  doc.fontSize(12).font('Helvetica-Bold').fillColor('#000').text('Email Details');
  doc.moveDown(0.5);

  doc.fontSize(10).font('Helvetica');
  doc.fillColor('#333').text(`From: ${applicantName || 'N/A'}`);
  doc.text(`To: ${recruiterName || 'N/A'} (${recruiterCompany || 'N/A'})`);
  doc.moveDown(1);

  // Subject
  doc.fontSize(11).font('Helvetica-Bold').fillColor('#000').text('Subject:');
  doc.fontSize(10).font('Helvetica').fillColor('#333').text(subject || 'No subject', { indent: 20 });
  doc.moveDown(1);

  // Body
  doc.fontSize(11).font('Helvetica-Bold').fillColor('#000').text('Email Body:');
  doc.moveDown(0.5);

  // Format body with proper paragraphs
  const paragraphs = (body || '').split('\n\n');
  doc.fontSize(10).font('Helvetica').fillColor('#000');

  paragraphs.forEach((para, index) => {
    // Handle line breaks within paragraphs
    const lines = para.split('\n');
    lines.forEach(line => {
      doc.text(line.trim(), { align: 'left', indent: 20 });
    });

    // Add spacing between paragraphs
    if (index < paragraphs.length - 1) {
      doc.moveDown(0.7);
    }
  });

  // Footer
  doc.moveDown(2);
  doc.strokeColor('#cccccc').lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(0.5);
  doc.fontSize(8).font('Helvetica-Oblique').fillColor('#999').text('Generated by YAAKE Career Platform', { align: 'center' });

  return doc;
}

/**
 * Export email as plain text format
 * @param {Object} emailData
 * @returns {string}
 */
function generateEmailText(emailData) {
  const { subject, body, applicantName, recruiterName, recruiterCompany, createdAt } = emailData;

  const lines = [
    '=' .repeat(60),
    'COLD OUTREACH EMAIL',
    '='.repeat(60),
    '',
    `Generated: ${new Date(createdAt || Date.now()).toLocaleString()}`,
    '',
    'FROM: ' + (applicantName || 'N/A'),
    'TO: ' + (recruiterName || 'N/A') + ' (' + (recruiterCompany || 'N/A') + ')',
    '',
    'SUBJECT: ' + (subject || 'No subject'),
    '',
    '-'.repeat(60),
    'EMAIL BODY:',
    '-'.repeat(60),
    '',
    body || 'No content',
    '',
    '='.repeat(60),
    'Generated by YAAKE Career Platform',
    '='.repeat(60)
  ];

  return lines.join('\n');
}

module.exports = {
  generateEmailPDF,
  generateEmailText
};
